### ISSUE TITLE
Module name changed to github.com/Fullscreen/aws-rotate-key causing issues with `go get`

### ISSUE THREAD

**Issue by dialupdisaster** [stefansundin/aws-rotate-key#20]
When you try to `go get` this project it now errors with the following:

```
go: downloading github.com/stefansundin/aws-rotate-key v1.0.7
go get: github.com/stefansundin/aws-rotate-key@v1.0.7: parsing go.mod:
        module declares its path as: github.com/Fullscreen/aws-rotate-key
                but was required as: github.com/stefansundin/aws-rotate-key
```

Even though master is correct the last tagged version has this incorrect module name.

**Comment by stefansundin** [comment]
Oh, did not think of this case. I guess it is time for me to merge #13 and release a new version, which should resolve this.

Thanks for reporting!

**Comment by stefansundin** [comment]
It looks like this works:

```
go install github.com/stefansundin/aws-rotate-key@master
```

`go get` seems to be deprecated for installing binaries. It prints a warning for me and it appears to be disabled in the upcoming Go 1.18.

**Comment by dialupdisaster** [comment]
I did not know of the deprecation thanks for that info. However `go get` will work also if you specify `master`. Neither command works if you specify `latest` instead of `master`. Maybe a new release can be generated with the proper namespace?

**Comment by stefansundin** [comment]
Yep, I definitely will. I was already thinking of making another release but I was going to wait for Go 1.18 (due to be released sometime in February).

**Comment by stefansundin** [comment]
v1.0.8 is now released and this issue appears to be fixed for me. Thanks again for reporting it!

I also added a tip to the README about installing with `go install`. 🎉
