### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by AlekKras** [stefansundin/aws-rotate-key#3]
That's not really an issue and feel free to close it, but I was thinking (and that's only a suggestion) about fully automating aws key rotation: what if a program can perform AWS API call to import all AWS IAM users, and create new keys per each user, store it in .csv file and then use AWS SNS service to notify each user about new keys? That would be cool to work on and that's what has been on my mind for the last few weeks and just today I came across your repo

**Comment by dstokes** [comment]
@AlekKras Great idea! It sounds a bit beyond the scope of this particular project but let us know if you come up with anything and we'll throw a link in the readme directing others to your project.
