### ISSUE TITLE
Add option flag to delete the old key after rotating

### ISSUE THREAD

**Issue by shentonfreude** [stefansundin/aws-rotate-key#4]
Would be a nice feature. 
Sorry, I'm not a gopher and don't know the Go AWS SDK.

**Comment by boroivanov** [comment]
Done with https://github.com/Fullscreen/aws-rotate-key/pull/6 by @ymatsiuk 

Released with https://github.com/Fullscreen/aws-rotate-key/releases/tag/v1.0.4

**Comment by boroivanov** [comment]
brew fullscreen/tap was updated.
