### ISSUE TITLE
Ubuntu 18.04 runtime error

### ISSUE THREAD

**Issue by mmota-pipefy** [stefansundin/aws-rotate-key#8]
Greetings,

When running the script manually it runs smooothly, but running it under cron i'm receiving the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x673d99]

goroutine 1 [running]:
main.main()
	/Users/bivanov/code/fs/aws-rotate-key/main.go:43 +0x2129
```

Any idea what that could be?

**Comment by stefansundin** [comment]
It's trying to find your credentials file using the `HOME` environment variable, which I don't think is set when cron executes things.

https://github.com/Fullscreen/aws-rotate-key/blob/d7d551fe440160298880547d6cc6a673c600d01d/main.go#L41-L44

So it might be fixable by setting `AWS_SHARED_CREDENTIALS_FILE` to the path of your credentials file. See https://stackoverflow.com/questions/3639415/variables-in-crontab

E.g:
```
AWS_SHARED_CREDENTIALS_FILE=/home/mmota/.aws/credentials
@daily /opt/aws-rotate-key -y
```

I haven't tested this, so please let us know if there are other errors.

But yes, we should check for this in the code and avoid an exception. :)

**Comment by mmota-pipefy** [comment]
It solved the problem.

Thanks.

**Comment by stefansundin** [comment]
Hi again @mmota-pipefy. I am trying to reproduce the error in order to have the program print a better error message, but I am not able to do it.

Could you share what your crontab looked like? Did you run it as root or your own user?

**Comment by stefansundin** [comment]
Judging by the go source code, it looks like it is reading the passwd file. https://github.com/golang/go/blob/97d5cb24b10b7b740de2f1cc04d88341c4437ae0/src/os/user/lookup_unix.go

So this may also be fixable with `usermod`.

In any case, I'm adding a check for this that will hopefully work and print a better error message.
